const MIN_KARAKTERA_OBJAVA_NASLOV = 5;
const MAX_KARAKTERA_OBJAVA_NASLOV = 25;

const MIN_KARAKTERA_OBJAVA_SADRZAJ = 25;

const MIN_KARAKTERA_KOMENTAR = 1;

const MIN_KARAKTERA_KORISNICKO_IME_SIFRA = 3;
const MAX_KARAKTERA_KORISNICKO_IME_SIFRA = 25;

module.exports.MIN_KARAKTERA_OBJAVA_NASLOV = MIN_KARAKTERA_OBJAVA_NASLOV;
module.exports.MAX_KARAKTERA_OBJAVA_NASLOV = MAX_KARAKTERA_OBJAVA_NASLOV;
module.exports.MIN_KARAKTERA_OBJAVA_SADRZAJ = MIN_KARAKTERA_OBJAVA_SADRZAJ;
module.exports.MIN_KARAKTERA_KOMENTAR = MIN_KARAKTERA_KOMENTAR;
module.exports.MIN_KARAKTERA_KORISNICKO_IME_SIFRA = MIN_KARAKTERA_KORISNICKO_IME_SIFRA;
module.exports.MAX_KARAKTERA_KORISNICKO_IME_SIFRA = MAX_KARAKTERA_KORISNICKO_IME_SIFRA;